### ISSUE TITLE
Automatisierte Codeanalyse mit PMD in GitHub Actions

### ISSUE THREAD

**Issue by johannes-b** [jku-win-se/teaching-2023.ws.prse.braeuer.team4#18]
## Automatisierte statische Codeanalyse mit PMD

Das Codeanalyse-Tool [PMD](https://pmd.github.io/) soll eingebaut werden, um die Qualität des Source Code zu gewährleisten. Die Analyse soll automatisiert mit jeder Code-Änderung ausgeführt werden. 

### Tasks
- [x] Den GitHub Workflow um folgende 2 Steps erweitern: 
```
- name: PMD Code Check
  uses: pmd/pmd-github-action@v1
  id: pmd
  with:
    version: '6.40.0'
    sourcePath: 'src/main/java'
    rulesets: 'ruleset.xml'

- name: Automatisierung bei einer Verletzung stoppen 
  if: steps.pmd.outputs.violations != 0
  run: exit 1
```
  - Achtung: Das Setting `sourcePath` anpassen, sollte der Source Code nicht unter `src/main/java` liegen. 
- [x] Die Datei `ruleset.xml` von [hier](https://github.com/jku-win-se/teaching.ws23.prse.prwiki.braeuer/blob/main/ruleset.xml) downloaden.
- [x] Die Datei `ruleset.xml` in das eigene Repository hinzufügen.

### Definition of Done
- [x] Die Ausführung der GitHub Action zeigt Regelverletzungen. z.B.: 
![image](https://github.com/jku-win-se/teaching-2023.ws.prse.braeuer.team2/assets/729071/34626e93-7125-43de-b9b3-edd7013a283d)
